name: Generate LaTeX PDF

on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/generate_document.yaml'

jobs:
  build-latex:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🧰 Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-base \
            texlive-latex-recommended \
            texlive-fonts-recommended \
            texlive-latex-extra \
            texlive-lang-german

      - name: 🛠 Compile LaTeX
        working-directory: ./docs
        run: pdflatex jobtinder_doku.tex

      - name: 📤 Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: jobtinder_doku.pdf
          path: docs/jobtinder_doku.pdf

