name: Render PlantUML diagrams with Kroki

on:
  push:
    paths:
      - 'diagrams/**/*.puml'
      - '.github/workflows/render_plantuml.yaml'
  pull_request:
    paths:
      - 'diagrams/**/*.puml'

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl jq

      - name: Render diagrams using Kroki API
        run: |
          mkdir -p diagrams/rendered
          for f in diagrams/*.puml; do
            filename=$(basename "$f" .puml)
            echo "Rendering $filename"
            content=$(cat "$f" | base64 | tr -d '\n')
            # Kroki API call: plantuml, format=svg
            curl -s -X POST https://kroki.io/plantuml/svg --data-binary "@$f" -o diagrams/rendered/"$filename".svg
          done

      - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.ACTIONS_PUSH_KEY }}

      - name: Set remote URL to SSH
        run: git remote set-url origin git@github.com:N0kta/Job-Tinder.git

      - name: Commit and push rendered diagrams
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add diagrams/rendered/
          git commit -m "Rendered PlantUML diagrams via Kroki" || echo "No changes to commit"
          git push origin HEAD:master


